var deckstub = [ { id: 'p',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'w',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'v',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'v',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'o',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'n',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'u',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'f',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'q',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'b',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'w',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'u',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'j',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'p',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'p',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'd',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'k',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'l',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'j',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'k',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'b',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'n',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'v',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'k',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'r',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'r',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'v',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'b',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'h',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'a',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'u',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'g',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'v',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'e',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'u',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'o',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'b',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'e',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'n',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'r',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'u',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'i',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'l',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'c',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'v',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 's',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'w',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'u',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'x',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'v',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'a',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'h',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 's',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'd',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'v',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'm',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'f',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'i',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'l',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'e',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 't',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'e',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'b',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'u',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'h',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'w',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'e',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'm',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'd',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'u',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'v',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'd',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined },
  { id: 'j',
    orientation: 0,
    x: undefined,
    y: undefined,
    meeple: undefined } ];

